### ISSUE TITLE
missing include dir

### ISSUE THREAD

**Issue by 7castle** [openbsod/webproxmgr#2]
### What you've tried already
Install repo. 

### Expected outcome
Minimalistic interface

### Actual outcome
Error 500

### Other information

Hello, I know it is just demo, but is it possible to put minimalistic version of 
include/config2.php ? 

* Operating System :
* Proxmox version :
* PHP version number : `php` and `composer` (`php -m`) 
* How did you install the proxmoxmgr :

**Comment by openbsod** [comment]
Hi.

I'll try to publish it soon. There is spaghetti code tho which need to be refactored.
